export enum ErrorCodes {
  CREATION_FAILED = "CREATION_FAILED",
  FETCH_FAILED = "FETCH_FAILED",
  NONE_NULL = "NONE_NULL",
  NOT_FOUND = "NOT_FOUND",
  DUPLICATE = "DUPLICATE",
  UNKNOWN = "UNKNOWN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  APP_ERROR = "APP_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
}
